name: Docker Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - 'challenge-1/**/*.py'
      - 'challenge-1/Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'challenge-1/**/*.py'
      - 'challenge-1/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./challenge-1 # Build context is set to challenge-1
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/intelygenz-webserver:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/intelygenz-webserver:${{ github.sha }}

    - name: Install Dive
      run: |
        wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
        sudo apt install ./dive_0.9.2_linux_amd64.deb

    - name: Run Dive
      run: |
        CI=true dive ${{ secrets.DOCKERHUB_USERNAME }}/intelygenz-webserver:${{ github.sha }} --config ./challenge-1/.dive-ci
